// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';fgl
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2XiU5SEIKAhkkGdMZ00oTBQUQ7KN1z3M',
    appId: '1:885992568398:web:7b736a4ed962fb5df2751f',
    messagingSenderId: '885992568398',
    projectId: 'thesis-jate1601',
    authDomain: 'thesis-jate1601.firebaseapp.com',
    storageBucket: 'thesis-jate1601.appspot.com',
    measurementId: 'G-X51FZEK5LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Pdl1EdxDFPLHvmfKENpx2MMf7IyxXr4',
    appId: '1:885992568398:android:037d218c802b33c0f2751f',
    messagingSenderId: '885992568398',
    projectId: 'thesis-jate1601',
    storageBucket: 'thesis-jate1601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArL_18X1AsO017pQVMPL0SDbAxpzPitTU',
    appId: '1:885992568398:ios:d5f28fe9fc081fedf2751f',
    messagingSenderId: '885992568398',
    projectId: 'thesis-jate1601',
    storageBucket: 'thesis-jate1601.appspot.com',
    iosBundleId: 'se.jate1601.thesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArL_18X1AsO017pQVMPL0SDbAxpzPitTU',
    appId: '1:885992568398:ios:09c645e0653166def2751f',
    messagingSenderId: '885992568398',
    projectId: 'thesis-jate1601',
    storageBucket: 'thesis-jate1601.appspot.com',
    iosBundleId: 'se.jate1601.thesis.RunnerTests',
  );
}
